#!/usr/bin/env python3
"""Build the public literature files for the data deposit.

Takes the working copies from the manuscript repository, removes the fields that
must not be published, and writes a REMOVED.md recording every removal and its
reason. The point is that the deposit is a mechanical, rerunnable transform of the
working files rather than a hand-edited copy nobody can check.

One thing is removed:

  File Attachments   absolute paths into the operating author's home directory,
                     which identify a person and point at PDFs nobody else has.

The short verbatim quotes in the C1--C5 Evidence columns stay. They carry the
whole auditability claim of the screen, since each criterion verdict is anchored
to the sentence it was based on. They are reproduced as quotation and remain the
property of their rights holders, which the deposit README states.

The deposit has two folders, delphi/ and literature/, and the analysis
repository unpacks it straight into its data/. Only the literature half is
built here. The Delphi half comes from the machine holding
the survey export, and audit_round4_export.py is the tool for that.

Usage:
    python scripts/prepare_public_data.py --source ../2025_PandemicGuidelines --out ../pg-deposit
"""
import argparse
import csv
import re
import shutil
import sys
from pathlib import Path

csv.field_size_limit(10_000_000)

# source path, deposit path, columns to drop, reason recorded in REMOVED.md
DROPS = [
    ("literature/articles-full-screen-results.csv",
     "literature/articles-full-screen-results.csv",
     ["File Attachments"],
     "absolute local filesystem paths containing a username"),
]

# copied unchanged, renamed to say what they are
COPIES = [
    ("literature/validation/theme_labels.csv", "literature/theme_labels_tuning.csv"),
    ("literature/validation/theme_labels_holdout.csv", "literature/theme_labels_holdout.csv"),
    ("literature/validation/theme_labels_holdout_clean.csv", "literature/theme_labels_holdout_clean.csv"),
]

# run over every output as a safety net
LEAKS = [
    (re.compile(r"[A-Za-z]:\\Users\\[^\\\s\"',;]+"), "Windows home directory path"),
    (re.compile(r"/(?:home|Users)/[^/\s\"',;]+"), "Unix home directory path"),
    (re.compile(r"[\w.+-]+@[\w-]+\.[\w.]+"), "email address"),
]


def strip_columns(src: Path, dst: Path, drop: list) -> tuple:
    with src.open(encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        cols = reader.fieldnames or []
        missing = [c for c in drop if c not in cols]
        if missing:
            sys.exit(f"error: {src.name} has no column(s) {missing}; "
                     f"the export format changed, check DROPS")
        keep = [c for c in cols if c not in drop]
        rows = list(reader)
    dst.parent.mkdir(parents=True, exist_ok=True)
    with dst.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=keep, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
    return len(rows), keep


def scan(path: Path) -> list:
    text = path.read_text(encoding="utf-8", errors="replace")
    hits = []
    for pattern, label in LEAKS:
        found = set(pattern.findall(text))
        if found:
            hits.append((label, sorted(found)[:5], len(found)))
    return hits


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--source", type=Path, required=True,
                    help="manuscript repository holding the working files")
    ap.add_argument("--out", type=Path, required=True,
                    help="deposit staging directory to write into")
    args = ap.parse_args()

    log = ["# What was removed from the deposited files",
           "",
           "Generated by `scripts/prepare_public_data.py`. Rerunning it on the",
           "working files reproduces this deposit exactly.",
           ""]
    findings = []

    for rel, out_rel, drop, reason in DROPS:
        src, dst = args.source / rel, args.out / out_rel
        if not src.exists():
            sys.exit(f"error: {src} not found")
        n, keep = strip_columns(src, dst, drop)
        print(f"  {out_rel}: {n} rows, dropped {drop}, kept {len(keep)} columns")
        log += [f"## `{out_rel}`", "",
                f"From `{rel}`. {n} rows. Removed the column(s) "
                f"`{'`, `'.join(drop)}`: {reason}. {len(keep)} columns remain.", ""]
        findings += [(dst, h) for h in scan(dst)]

    for rel, out_rel in COPIES:
        src, dst = args.source / rel, args.out / out_rel
        if not src.exists():
            sys.exit(f"error: {src} not found")
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        print(f"  {out_rel}: copied unchanged")
        log += [f"## `{out_rel}`", "",
                f"From `{rel}`, copied unchanged. Nothing removed.", ""]
        findings += [(dst, h) for h in scan(dst)]

    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "REMOVED.md").write_text("\n".join(log), encoding="utf-8")

    if findings:
        print("\nREVIEW THESE BEFORE PUBLISHING:")
        for path, (label, sample, count) in findings:
            print(f"  {path.name}: {count} x {label}, e.g. {sample}")
        sys.exit(1)
    print("\nNo home directory paths or email addresses found in the output.")


if __name__ == "__main__":
    main()
